# https://docs.travis-ci.com/user/reference/xenial/#using-xenial
dist: xenial

# set up MySQL database
# https://docs.travis-ci.com/user/database-setup/#mysql
services:
  - mysql

env:
  - TEST_DATABASE=mycroft_holmes TEST_DATABASE_USER=travis TEST_DATABASE_PASSWORD=''

before_script:
  - mysql -e 'CREATE DATABASE mycroft_holmes;'
  - cat schema.sql | mysql mycroft_holmes

after_script:
  - mysql mycroft_holmes -e 'SELECT * FROM features_metrics'

language: python
python:
    - "3.6"
    - "3.7"

# command to install dependencies
install: "make"

# command to run tests
script:
    - make coverage
    - make lint
