# https://docs.travis-ci.com/user/reference/xenial/#using-xenial
dist: xenial

services:
  - mysql

language: python
python:
    - "3.5"
    - "3.6"
    - "3.7-dev"

# command to install dependencies
install: "make"

# command to run tests
script:
    - make coverage
    - make lint
